name: main

on:
  push:
    branches:
      - 'main'

env:
  TEST_TAG: rommaa/soccer-stat:test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      # - run: make test
      - run: docker run --rm ${{ env.TEST_TAG }} npm lint

      - name: Build and push app
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rommaa/soccer-stat:latest
